### ISSUE TITLE
Added some rules to Atom version

### ISSUE THREAD

**Issue by smlombardi** [Briles/gruvbox#7]
I'm not sure you're aware, but I have ported your excellent theme [to Atom](https://atom.io/themes/gruvbox-syntax) a while back.  I just rolled your latest additions into the Atom version, and while using it I noticed a few scss rules that I felt were missing, so I added the following, trying to keep the look similar to the theme:

```scss
.meta.at-rule.mixin.scss .entity.name.function.scss {
  color: #fe8019;
}

.meta.at-rule.mixin.scss .keyword.control.at-rule.mixin.scss {
  color: #fb4934;
}
.keyword.control.at-rule.mixin.scss .punctuation.definition.keyword.scss {
  color: #cc421d;
}

.meta.at-rule.else.scss .keyword.control.else.scss, .meta.at-rule.if.scss .keyword.control.if.scss {
  color:#fabd2f;
}
.keyword.control.else.scss .punctuation.definition.keyword.scss, .keyword.control.if.scss .punctuation.definition.keyword.scss {
  color: #d79921;
}

.meta.at-rule.return.scss .keyword.control.return.scss {
  color: #fe8019;
}
.keyword.control.return.scss .punctuation.definition.keyword.scss {
  color: #d65d0e;
}

.meta.at-rule.media.scss .keyword.control.at-rule.media.scss {
  color: #689d6a;
}
.keyword.control.at-rule.media.scss .punctuation.definition.keyword.scss {
  color: #8ec07c;
}
.meta.content.scss .keyword.control.content.scss {
  color: #d5c4a1;
  font-style: italic;
}
```

Should these items be colored differently, in your opinion?
